<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="template" nsURI="http://www.obeonetwork.org/m2doc/template/1.0"
    nsPrefix="template">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="documentation" value="This metamodel describes the M2Doc abstract syntax tree."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IConstruct" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleRun" eType="#//Run"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runs" upperBound="-1" eType="#//Run"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closingRuns" upperBound="-1"
        eType="#//Run"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMessages" upperBound="-1"
        eType="#//TemplateValidationMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Statement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="A comment produce nothing in the generated document."/>
      <details key="syntax" value="{m:comment &lt;comment text>}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="#//Statement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="If {@link Conditional#getCondition() condition} is evaluated to &lt;code>true&lt;/code> the {@link Conditional#getThen() then} {@link Compound} is executed, otherwise the {@link Conditional#getElse() else} {@link Compound}"/>
      <details key="syntax" value="{m:if expr} runs1 [{m:elseif &lt;expr>} runs_n]* [{m:else} run_else]{m:endif}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="#//AstResult">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="If evaluated to &lt;code>true&lt;/code> the {@link Conditional#getThen() then} {@link Compound} is executed, otherwise the {@link Conditional#getElse() else} {@link Compound}"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="The {@link Compound} is executed if {@link Conditional#getCondition() condition} is evaluated to &lt;code>true&lt;/code>."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="The {@link Compound} is executed if {@link Conditional#getCondition() condition} is evaluated to &lt;code>false&lt;/code>."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repetition" eSuperTypes="#//Statement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="This produce the {@link Repetition#getBody() body} for each value of the {@link Repetition#getQuery() query} evaluation result. More inforamation about &lt;a href=&quot;https://www.eclipse.org/acceleo/documentation/aql.html&quot;>Acceleo Query Language&lt;/a>."/>
      <details key="syntax" value="{m:for var | query} body {m:endfor}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iterationVar" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" lowerBound="1" eType="#//AstResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="The {@link Block} of {@link Statement}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDoc" eSuperTypes="#//Statement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="UserDoc  tag&#xD;&#xA;&#xD;&#xA;Tag template to keep user part modification in previous generated &#xD;&#xA;result file."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="#//AstResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="The {@link Block} of {@link Statement}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserContent" eSuperTypes="#//Statement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="UserDocDest  tag&#xD;&#xA;&#xD;&#xA;Tag in generated document neede to extract user part modification.&#xD;&#xA;UserDocDest is generated by M2Doc&#xD;&#xA;&#xD;&#xA;."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="The {@link Block} of {@link Statement}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query" eSuperTypes="#//Statement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="The query produce the {@link Query#getQuery() query} evaluation result in the produced document. More inforamation about &lt;a href=&quot;https://www.eclipse.org/acceleo/documentation/aql.html&quot;>Acceleo Query Language&lt;/a>."/>
      <details key="syntax" value="{m:&lt;aql query>}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" lowerBound="1" eType="#//AstResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//AbstractImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//IConstruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" interface="true"
      eSuperTypes="#//IConstruct"/>
  <eClassifiers xsi:type="ecore:EClass" name="Template" eSuperTypes="#//IConstruct">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="XWPFBody" eType="#//Body"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="The {@link Block} of {@link Statement}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="InputStream" instanceClassName="java.io.InputStream"/>
  <eClassifiers xsi:type="ecore:EDataType" name="OPCPackage" instanceClassName="org.apache.poi.openxml4j.opc.OPCPackage"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Document" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFDocument"/>
  <eClassifiers xsi:type="ecore:EDataType" name="WTable" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFTable"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Run" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFRun"/>
  <eClassifiers xsi:type="ecore:EClass" name="Representation" eSuperTypes="#//AbstractImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" lowerBound="1" eType="#//AstResult"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representationTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activatedLayers" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticFragment" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="QueryBehavior">
    <eLiterals name="ICON"/>
    <eLiterals name="LABEL" value="1"/>
    <eLiterals name="TEXT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AstResult" instanceClassName="org.eclipse.acceleo.query.runtime.IQueryBuilderEngine.AstResult"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TemplateValidationMessage" instanceClassName="org.obeonetwork.m2doc.parser.TemplateValidationMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//Row"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="#//WTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableRow" eType="#//WTableRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableCell" eType="#//WTableCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="WTableRow" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFTableRow"/>
  <eClassifiers xsi:type="ecore:EDataType" name="WTableCell" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFTableCell"/>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" upperBound="-1"
        eType="#//Template" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="footers" upperBound="-1"
        eType="#//Template" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputStream" lowerBound="1"
        eType="#//InputStream"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opcPackage" lowerBound="1"
        eType="#//OPCPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="document" lowerBound="1"
        eType="#//Document"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="POSITION">
    <eLiterals name="ABOVE"/>
    <eLiterals name="BELOW" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionValueMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractImage" abstract="true" eSuperTypes="#//AbstractProviderClient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legendPOS" eType="#//POSITION"
        defaultValueLiteral="BELOW"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Provider" instanceClassName="org.obeonetwork.m2doc.provider.IProvider"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProviderClient" abstract="true"
      eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionValueMap" upperBound="-1"
        eType="#//OptionValueMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="#//Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Body" instanceClassName="org.apache.poi.xwpf.usermodel.IBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bookmark" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//AstResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="The {@link Block} of {@link Statement}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//AstResult"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="#//AstResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Let" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//AstResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="The {@link Block} of {@link Statement}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableClient" eSuperTypes="#//AbstractProviderClient"/>
</ecore:EPackage>
