<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="template" nsURI="http://www.obeonetwork.org/m2doc/template/1.0"
    nsPrefix="template">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="documentation" value="Le méta modèle 'template' représente les concepts produit par le parsing &#xD;&#xA;des templates de génération documentaire.&#xD;&#xA;&#xD;&#xA;Les modèles instances sont utilisés pour la génération."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConstruct" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleRun" eType="#//Run"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runs" upperBound="-1" eType="#//Run"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closingRuns" upperBound="-1"
        eType="#//Run"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMessages" upperBound="-1"
        eType="#//TemplateValidationMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conditionnal" eSuperTypes="#//Compound">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="AlternativeExcludeElse"/>
      <details key="documentation" value="Si l'expression expr est évaluée à true dans le contexte courant alors l'ensemble de la balise jusqu'à la balise gd:endif comprisee est remplacée par le traitement de runs1 dans le contexte courant. Sinon, l'ensemble des balises est remplacée par le traitement du premier run_n tel que l'expression expr de la balise gd:elseif associée est évaluée à vrai. Si aucune telle balise n'est présente ou si aucune d'entre-elle porte une expression évaluée à true, le résultat du traitement de run_else, si la balise gd:else est présente, dans le contexte courant est inséré à la place de l'ensemble des balises"/>
      <details key="syntax" value="{gd:if expr} runs1 [{gd:elseif &lt;expr>} runs_n]* [{gd:else} run_else]{gd:endif}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" eType="#//Conditionnal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Default"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="#//AstResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repetition" eSuperTypes="#//Compound">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="pour chaque valeur v dans le résultat de l'évaluation de query, &#xD;&#xA;- un nouveau contexte est crée en ajoutant la définition 'var =v' au contexte courant&#xD;&#xA;- le résultat du traitement du corps runs est inséré dans le document &#xD;&#xA;les balises {gd:for} et {gd:endfor} sont supprimées.&#xD;&#xA;Si la balise {gd:for} est immédiatement suivie d'un retour chariot alors l'ensemble du paragraphe la contenant est supprimée du résultat sinon, le paragraphe duquel on a supprimé la balise est inséré dans le résultat. Le même traitement est appliqué à la balise {gd:endfor}"/>
      <details key="syntax" value="{gd:for var | query} body {gd:endfor}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iterationVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="#//AstResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDoc" eSuperTypes="#//Compound">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="UserDoc  tag&#xD;&#xA;&#xD;&#xA;Tag template to keep user part modification in previous generated &#xD;&#xA;result file."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="#//AstResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserContent" eSuperTypes="#//Compound">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="UserDocDest  tag&#xD;&#xA;&#xD;&#xA;Tag in generated document neede to extract user part modification.&#xD;&#xA;UserDocDest is generated by M2Doc&#xD;&#xA;&#xD;&#xA;."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query" eSuperTypes="#//AbstractConstruct">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="documentation" value="La balise est remplacée dans le document par la représentation en &#xD;&#xA;chaine de caractère du résultat de l'évaluation de l'expression dans le &#xD;&#xA;contexte courant. La style du premier run contenant query est utilisé pour générer le document. Il n'y a pas de sens à utiliser plusieurs styles différents dans une requête si bien que seul le premier est utilisé si plusieurs sont présents.&#xD;&#xA;- Lorsque le modifier icon est précisé, l'icone de l'élément évalué telle que définie dans le .edit correspondant  est insérée à la place du run&#xD;&#xA;- Lorsque le modifier label est précisé, le label de l'élément évalué tel que définin dans le .edit correspondant est inséré à la place du run.&#xD;&#xA;- Lorsque le modifier text ou qu'aucun modifier n'apparait, la représentation en chaine de caractère de l'évaluation du résultat est inséré."/>
      <details key="syntax" value="{aql:query [icon, label,text]}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behavior" eType="#//QueryBehavior"
        defaultValueLiteral="TEXT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="#//AstResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableMerge" eSuperTypes="#//Compound">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//AbstractImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Default" eSuperTypes="#//Compound"/>
  <eClassifiers xsi:type="ecore:EClass" name="Compound" abstract="true" eSuperTypes="#//AbstractConstruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subConstructs" upperBound="-1"
        eType="#//AbstractConstruct" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template" eSuperTypes="#//Compound">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="#//Body"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Document" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFDocument"/>
  <eClassifiers xsi:type="ecore:EDataType" name="WTable" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFTable"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Run" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFRun"/>
  <eClassifiers xsi:type="ecore:EClass" name="Representation" eSuperTypes="#//AbstractImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="#//AstResult"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representationTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activatedLayers" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticFragment" eSuperTypes="#//AbstractConstruct"/>
  <eClassifiers xsi:type="ecore:EEnum" name="QueryBehavior">
    <eLiterals name="ICON"/>
    <eLiterals name="LABEL" value="1"/>
    <eLiterals name="TEXT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AstResult" instanceClassName="org.eclipse.acceleo.query.runtime.IQueryBuilderEngine.AstResult"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TemplateValidationMessage" instanceClassName="org.obeonetwork.m2doc.parser.TemplateValidationMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//AbstractConstruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//Row"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="#//WTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableRow" eType="#//WTableRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableCell" eType="#//WTableCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="WTableRow" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFTableRow"/>
  <eClassifiers xsi:type="ecore:EDataType" name="WTableCell" instanceClassName="org.apache.poi.xwpf.usermodel.XWPFTableCell"/>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" upperBound="-1"
        eType="#//Template" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="footers" upperBound="-1"
        eType="#//Template" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="document" eType="#//Document"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="POSITION">
    <eLiterals name="ABOVE"/>
    <eLiterals name="BELOW" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionValueMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractImage" abstract="true" eSuperTypes="#//AbstractProviderClient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legendPOS" eType="#//POSITION"
        defaultValueLiteral="BELOW"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Provider" instanceClassName="org.obeonetwork.m2doc.provider.IProvider"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProviderClient" abstract="true"
      eSuperTypes="#//AbstractConstruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionValueMap" upperBound="-1"
        eType="#//OptionValueMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="#//Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Body" instanceClassName="org.apache.poi.xwpf.usermodel.IBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bookmark" eSuperTypes="#//Compound">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//AstResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//AbstractConstruct">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//AstResult"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="#//AstResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableClient" eSuperTypes="#//AbstractProviderClient"/>
</ecore:EPackage>
